# Generated by Django 5.1.2 on 2025-01-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0003_alter_books_about_book_alter_books_author_and_more'),
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='author',
            name='books_published',
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='books_published',
            field=models.ManyToManyField(related_name='authors', to='AppOne.books'),
        ),
    ]
