# Generated by Django 5.1.4 on 2024-12-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='about_book',
            field=models.CharField(max_length=200),
        ),
    ]
