# Generated by Django 5.1.2 on 2025-01-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0002_alter_books_about_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='about_book',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
